  create or replace function public.set_updated_at()
  returns trigger
  language plpgsql
  as $$
  begin
    new.updated_at = now();
    return new;
  end;
  $$;

  create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    username text not null unique,
    full_name text,
    password_hash text not null,
    role text not null check (role in ('Super Admin', 'Admin', 'Account Officer 1', 'Account Officer 2', 'Account Officer 3', 'User')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  alter table public.users drop constraint if exists users_role_check;
  update public.users
  set role = replace(role, 'Assistant Officer', 'Account Officer')
  where role like 'Assistant Officer %';
  alter table public.users add constraint users_role_check
    check (role in ('Super Admin', 'Admin', 'Account Officer 1', 'Account Officer 2', 'Account Officer 3', 'User'));

  create table if not exists public.employers (
    id bigint generated by default as identity primary key,
    assigned_view text not null check (assigned_view in ('AO1', 'AO2', 'AO3')),
    employer_number text not null,
    employer_name text not null,
    address text,
    address_line1 text,
    address_country text,
    address_state text,
    address_city text,
    address_barangay text,
    address_postal_code text,
    principal numeric(12, 2) not null default 0,
    penalty numeric(12, 2) not null default 0,
    interest numeric(12, 2) not null default 0,
    total_amount numeric(12, 2) not null default 0,
    billing_date date,
    person_received text,
    coverage_date date,
    soa_date date,
    employee_count integer,
    payment_principal numeric(12, 2),
    payment_interest numeric(12, 2),
    payment_penalty numeric(12, 2),
    payment_total numeric(12, 2),
    soa2_date date,
    soa3_date date,
    legal_referral_date date,
    demand_letter_date date,
    demand_letter_received_date date,
    handling_lawyer text,
    docket_number text,
    case_date date,
    status text not null check (status in ('Settled', 'Unsettled', 'Registed', 'Not Yet Registered')),
    created_at timestamptz not null default now()
  );

  create table if not exists public.calendar_events (
    id bigint generated by default as identity primary key,
    title text not null,
    event_date date not null,
    start_time time,
    end_time time,
    description text,
    created_by uuid references public.users(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint calendar_events_time_order check (start_time is null or end_time is null or end_time > start_time)
  );

  alter table public.calendar_events alter column start_time drop not null;
  alter table public.calendar_events alter column end_time drop not null;
  alter table public.calendar_events drop constraint if exists calendar_events_time_order;
  alter table public.calendar_events add constraint calendar_events_time_order
    check (start_time is null or end_time is null or end_time > start_time);

  alter table public.employers add column if not exists employee_count integer;
  alter table public.employers add column if not exists address_line1 text;
  alter table public.employers add column if not exists address_country text;
  alter table public.employers add column if not exists address_state text;
  alter table public.employers add column if not exists address_city text;
  alter table public.employers add column if not exists address_barangay text;
  alter table public.employers add column if not exists address_postal_code text;
  alter table public.employers add column if not exists person_received text;
  alter table public.employers add column if not exists payment_principal numeric(12, 2);
  alter table public.employers add column if not exists payment_interest numeric(12, 2);
  alter table public.employers add column if not exists payment_penalty numeric(12, 2);
  alter table public.employers add column if not exists payment_total numeric(12, 2);
  alter table public.employers add column if not exists soa2_date date;
  alter table public.employers add column if not exists soa3_date date;
  alter table public.employers add column if not exists legal_referral_date date;
  alter table public.employers add column if not exists demand_letter_date date;
  alter table public.employers add column if not exists demand_letter_received_date date;
  alter table public.employers add column if not exists handling_lawyer text;
  alter table public.employers add column if not exists docket_number text;
  alter table public.employers add column if not exists case_date date;

  create index if not exists employers_assigned_view_idx on public.employers (assigned_view);
  create index if not exists calendar_events_event_date_idx on public.calendar_events (event_date);
  create index if not exists users_role_idx on public.users (role);
  create index if not exists users_username_idx on public.users (username);

  alter table public.users enable row level security;
  alter table public.employers enable row level security;
  alter table public.calendar_events enable row level security;

  drop policy if exists "Users can read their own account" on public.users;
  create policy "Users can read their own account" on public.users
    for select using (false);

  drop policy if exists "Admins can read all users" on public.users;
  create policy "Admins can read all users" on public.users
    for select using (false);

  drop trigger if exists set_users_updated_at on public.users;
  create trigger set_users_updated_at
  before update on public.users
  for each row
  execute procedure public.set_updated_at();